################################
# Backend Development Container
################################

FROM python:3-alpine3.6
MAINTAINER Computer Science House (evals@csh.rit.edu)

# Expose the application port
EXPOSE 6969

# Add the app user
RUN adduser -u 1000 -S conditional

# Set the working directory to the mounted volume
WORKDIR /opt/conditional

# Install some additional packages required for dependencies,
# then configure OpenLDAP to use the system trusted CA store
RUN apk add --no-cache \
        ca-certificates \
        gcc \
        libffi-dev \
        libressl-dev \
        musl-dev \
        openldap-dev \
        postgresql-client \
        postgresql-dev \
    && update-ca-certificates \
    && echo "tls_cacertdir /etc/ssl/certs" >> /etc/openldap/ldap.conf

# Install Python dependencies
ADD requirements.txt /tmp
RUN pip install --no-cache-dir -r /tmp/requirements.txt \
    && rm -f /tmp/requirements.txt

# Add wait-for-postgres
ADD tools/wait-for-postgres.sh /opt
RUN chmod 755 /opt/wait-for-postgres.sh

# Drop privileges
USER conditional

# Run the build and start the application
CMD ["/opt/wait-for-postgres.sh", "python", "app.py"]
